### ISSUE TITLE
Bloated test and dev dependencies

### ISSUE THREAD

**Issue by devkral** [dymmond/esmerald#304]
The docs say, you have to install test for the testclient and dev for a dev server. But there are many seemingly not required dependencies included:

faker
freezegun
flask
db stuff
type checking stuff
...

I think you mixed together libraries used by you for tests and libraries for tests for endusers.

My recommendation would be to use an (hatch) environment instead for the internal used dependencies 

For dev it is the same, it contains only one library for endusers: a2wsgi

**Comment by devkral** [comment]
anyway: why requests, werkzeug and httpx in the same project? What blocks you from migrating to httpx only?

**Comment by tarsil** [comment]
@devkral apologies and you are correct. Actually those were needed in the past but since version 2 a few were not used anymore and potentially could be removed. 

I'm more than happy to have some PRs with suggestions from you as well 🙂

**Comment by tarsil** [comment]
Any good improvement and suggestions are more than welcomed and you seem keen to make it better which we do all appreciate it 🙂

**Comment by devkral** [comment]
I am short in time, but I will try ;).
I think this project could be a successor to django, as like as edgy to to saffier.

**Comment by tarsil** [comment]
Thank you so much for the kind words @devkral , truly. The goal is to be simple yet complex when needed and familiar to everyone. 

Edgy and Saffier were with the same goal and both serve different purposes 🙂, one 100% pydantic built and the other more pure orm, no pydantic oriented
