### ISSUE TITLE
encoders extra incorrect

### ISSUE THREAD

**Issue by devkral** [dymmond/esmerald#305]
The docs say, it should include ujson and orjson but includes only the first.

Anyway, why would anyone need such an extra? People can select the library themselves

**Comment by devkral** [comment]
sry was too fast, shall I reopen it as discussion?

**Comment by tarsil** [comment]
You can indeed. You might be referring to ojson as it is internally used for some automatic parsing in the response but there is indeed something that needs to be updated in the encoders which is actually being even renamed to something else as we are adding some changes in the coming versions

**Comment by tarsil** [comment]
This was also addressed 👍🏼
